Milestone 4
MephistoDevelop/fakebook pull request #5
Opened 2019-10-18 21:04 UTC by serdg0

2019-10-18 21:30 UTC, samgaco requested changes
Hi @MephistoDevelop and @serdg0 :high_brightness: 

Before proceeding we have the following points to address;

- [x] Users should be able to comment on posts for this milestone (right now there is no option for doing so)

> ![fbcomments](https://user-images.githubusercontent.com/34820784/67129384-d213a200-f1fe-11e9-9b41-b3f2ed144e2f.png)


- [x] All the test should be passing (now there are some failed test), if some of those tests are testing   features that are yet to be implemented you can use [pending](https://relishapp.com/rspec/rspec-core/v/2-0/docs/pending/pending-examples), example;

```
describe "an example" do
  it "is implemented but waiting" do
    pending("something else getting finished")
    this_should_not_get_executed
  end
end
```

- [x] All the queries in views should be actually seen in the models, not in the views


------------------------------

moving on :arrow_down: 

* **[For your next code review requests]**  Add a short summary of changes in Pull Request description

-----------------------------

* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-10-18 21:30 UTC, samgaco commented on app/views/posts/index.html.erb
> +  comment author: <%= User.where(id: comment.author_id).pluck(:username).first %><br>
- [ ] **[REQUIRED]** Try to keep queries in the models (users model in this case), you can style it as a scope or an association for example.

2019-10-21 17:16 UTC, MephistoDevelop commented
Fixed:
- [Add Comments in a posts]
 - [ Fixed test to green]
- [Add helpers to do querys and used in views]

![testsfakebook](https://user-images.githubusercontent.com/19605034/67227098-23d54b80-f3fc-11e9-9841-055253f500dc.png)

2019-10-21 20:25 UTC, Oghenebrume50 approved these changes
**STATUS:   APPROVED** :+1: 
Hi Team, good job, all issues were worked on and they passed :smile:, now just an optional suggestion.

[OPTIONAL], consider making comment available when a user views an individual post, currently commenting is only possible when viewing all posts. This is implementation details but a very good one

Please move on to the next milestone and code away. 

**RAPHAEL NORIODE**

2019-10-22 23:44 UTC, merged