Milestone 5
MephistoDevelop/fakebook pull request #6
Opened 2019-10-22 23:45 UTC by serdg0

Friendship V1

2019-10-23 19:30 UTC, mosaaleb requested changes
### Well done @serdg0 @MephistoDevelop :clap:

#### You did a great job handling all the friendship associations. Yet there are some requirements needs handling before moving on.

- [x] **`[OPTIONAL]`** sender sent a friend request to receiver. reciever can't send a friend request to sender.

We can achieve this by adding interchangeable validation to check if the [user_id, friend_id] or [friend_id, user_id] exist in the friendship table. [please take a look at this example](https://stackoverflow.com/questions/29123620/rails-validate-unique-friendship-relationships)

- [x] **`[OPTIONAL]`** Previous step adds model validations to friendships uniqueness. I would suggest to add interchangeable DB validations. You need to know first why DB validations are important [why](https://thoughtbot.com/blog/the-perils-of-uniqueness-validations). 
My previous code partner wrote an article on how to achieve [this](https://www.freecodecamp.org/news/how-to-set-unique-interchangeable-index-constraint-in-rails/).

- [x] We haven't written and friendship or user models tests for friendship feature yet. Let's add tests to test associations and all instance method in `user.rb`.

- [x] There is a failing test in your test suite. Let's fix it:
![Screenshot from 2019-10-23 21-14-45](https://user-images.githubusercontent.com/4246637/67426329-28575b00-f5da-11e9-869a-a8a2f0433d99.png)


#### Please handle these requirements and submit a new code review.

#### Happy Coding :computer:

**Muhammad Ebeid**

2019-10-23 19:30 UTC, mosaaleb commented on app/models/friendship.rb
> +  def user_requestor
- [x] `user_requestor` and `user_requested` method are kind of redundant. If you want to get the requestor of a specific friendship, you can use the `belongs_to` association above:
```ruby
friendship_instance.requestor
friendship_instance.requested
```

2019-10-24 06:51 UTC, Oghenebrume50 requested changes
### STATUS: CHANGES REQUIRED
Hi Team, good progress on this :+1: , everything works fine the only thing left are test for this milestone, the previous reviewer mentioned it, I guess you guys somehow skipped it. I cannot see test written for this implementation.

Please make changes and request for another review :+1:  

**Raphael Noriode**

2019-10-25 19:09 UTC, Oghenebrume50 approved these changes
### Status: Approved

Good Job Team :+1:  Everything works now, this is approved.

**Raphael Noriode**

2019-10-25 20:02 UTC, merged