Milestone 6
MephistoDevelop/fakebook pull request #7
Opened 2019-10-25 18:43 UTC by serdg0

2019-10-26 13:36 UTC, efrapp requested changes
## We need to make some improvements 🔧🔨 
Hi @MephistoDevelop and @serdg0 👋. You are doing a great job so far. However, you need to go a step further and I sure you can do it because your code reflects organization and a good understanding of the features.

The idea in this last project is that you apply all the main concepts you learned from previous ones, I'm specifically talking about associations. Actions like get `confirmed_friendships` or `pending_friendships` should be modeled with associations instead of using objects processing. The main benefit of this is that your queries will be faster because associations internally are using SQL queries and they are faster than processing objects using methods.

Another point I want to mention is that you don't rely on your friendships controller (you don't even have one) and some of the actions you already have in your users controller are responsibility of your friendships controller.

To summarize, the required changes are the following:
- [x] Use `:through` associations to get information like friends or pending requests of a user
- [x] Move actions from users controller that are responsibility of your friendships controller
- [x] I got an inconsistency when I was tenting the friendship feature: I created a user called `gipsy` that doesn't have a friendship (nor pending request) with other users but when I check the list of users from her session she appears with a `Delete Friend mafe` but they aren't friends, see #8.
- [x] PostsController#index displays posts in a timeline (**their own posts + posts from their friends**)

Please send a new code review with the changes and if I didn't explain well something, please, let me know on Slack (@Efrain).

**Status:** `Changes required`

2019-10-26 13:36 UTC, efrapp commented on app/controllers/users_controller.rb
> +  end
Guys, this can be a task in your friendships controller. In that way, you can preserve the standard names for the controller's actions. Please, check the following article about standard names for actions: http://jeromedalbert.com/how-dhh-organizes-his-rails-controllers/

2019-10-26 13:36 UTC, efrapp commented on app/controllers/users_controller.rb
> +  end
The same case here, this task should be the responsibility of the friendships controller.

2019-10-26 13:36 UTC, efrapp commented on app/models/user.rb
> +  end
Instead of use object processing, you can use a `:through` association to get the same with faster results.

2019-10-30 14:29 UTC, AdnanAfsari approved these changes
**Status: Approved**

Hello @serdg0 @MephistoDevelop ✋ 

Great work.You have made all the changes the previous reviewer requested.Its a 👍 from me.

Happy Coding
Adnan Afsari

2019-10-30 20:13 UTC, merged